version: '3.7'

services:
    db:
        container_name: postgres-miodly
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=${POSTGRES_DATABASE}
        ports:
            - 5433:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - miodly-backend

    redis:
        container_name: redis-miodly
        image: redis:5.0
        restart: always
        ports:
            - 6379:6379
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - redis_data:/data
        networks:
            - miodly-backend

volumes:
    postgres_data:
    redis_data:

networks:
    miodly-backend:
